/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import logica.Contador;


/**
 *
 * @author Estudiantes
 */
public class guiContador extends javax.swing.JFrame {
    private Contador contador = new Contador(); 
    /**
     * Creates new form NewJFrame
     */
    public guiContador() {
        initComponents();
        LBLvalor.setText(String.valueOf(contador.getValor()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLetiquetadevalor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LBLvalor = new javax.swing.JLabel();
        BTNcontador = new javax.swing.JButton();
        BTNdescontar = new javax.swing.JButton();
        BTNborrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("3ds", 0, 18)); // NOI18N

        LBLetiquetadevalor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LBLetiquetadevalor.setText("valor:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("contador poo G87");

        LBLvalor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBLvalor.setText("0");

        BTNcontador.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BTNcontador.setText("contar");
        BTNcontador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcontadorActionPerformed(evt);
            }
        });

        BTNdescontar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BTNdescontar.setText("descontar");
        BTNdescontar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNdescontarActionPerformed(evt);
            }
        });

        BTNborrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BTNborrar.setForeground(new java.awt.Color(255, 0, 51));
        BTNborrar.setText("borrar");
        BTNborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNborrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNcontador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNdescontar)
                        .addGap(74, 74, 74)
                        .addComponent(BTNborrar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBLetiquetadevalor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBLvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLetiquetadevalor)
                    .addComponent(LBLvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNcontador)
                    .addComponent(BTNdescontar)
                    .addComponent(BTNborrar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNcontadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcontadorActionPerformed
        // TODO add your handling code here:
        contador.avanzar();
        LBLvalor.setText(String.valueOf(contador.getValor()));
    }//GEN-LAST:event_BTNcontadorActionPerformed

    private void BTNdescontarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNdescontarActionPerformed
        // TODO add your handling code here:
        contador.retroceder();
        LBLvalor.setText(String.valueOf(contador.getValor()));
    }//GEN-LAST:event_BTNdescontarActionPerformed

    private void BTNborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNborrarActionPerformed
        // TODO add your handling code here:
        contador.borrar();
        LBLvalor.setText(String.valueOf(contador.getValor()));
    }//GEN-LAST:event_BTNborrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiContador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiContador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNborrar;
    private javax.swing.JButton BTNcontador;
    private javax.swing.JButton BTNdescontar;
    private javax.swing.JLabel LBLetiquetadevalor;
    private javax.swing.JLabel LBLvalor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
